### ISSUE TITLE
Throws if module has no entry point

### ISSUE THREAD

**Issue by topaxi** [stefanpenner/hash-for-dep#22]
If a module (like `babel-runtime`) has no entry point (no `index.js` nor `main` defined in `package.json`), The `resolvePkg()` functions throws with `Cannot find module 'babel-runtime/'`.

I'm unsure how this could be fixed.

**Comment by stefanpenner** [comment]
> I'm unsure how this could be fixed.

it just needs to find the dir root. of the given module
