### ISSUE TITLE
yarn PNP support

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/hash-for-dep#47]
Proposal

* consider dependencies in yarn global cache immutable
* only deeply hash local and linked dependencies

cc @rwjblue @turbo87

**Comment by stefanpenner** [comment]
yarn PR https://github.com/yarnpkg/rfcs/pull/101

**Comment by stefanpenner** [comment]
cc @dcombslinkedin

**Comment by dcombslinkedin** [comment]
Thanks, @stefanpenner . I'm starting to take a look at this stuff right now. It certainly sounds like a good proposal overall!

**Comment by stefanpenner** [comment]
- [ ] . https://github.com/stefanpenner/hash-for-dep/pull/55
